# Generated by Django 3.1 on 2020-08-31 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql = 'ALTER TABLE item_item add column image bytea; ',
            reverse_sql = 'ALTER TABLE item_item DROP column image'
        ),
    ]
